// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemEgzaminow.Data.Context;

#nullable disable

namespace SystemEgzaminow.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708175329_FixPytanieAutorRelation")]
    partial class FixPytanieAutorRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemEgzaminow.Core.Models.LogLogowania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CzySukces")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataLogowania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataWylogowania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sesja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("LogiLogowan");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.LogRozwiazywaniaTestu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataZdarzenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrzypisanyTestId")
                        .HasColumnType("int");

                    b.Property<string>("TypZdarzenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrzypisanyTestId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("LogiRozwiazywaniaTestu");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Odpowiedz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyPoprawna")
                        .HasColumnType("bit");

                    b.Property<int?>("LiczbaPunktow")
                        .HasColumnType("int");

                    b.Property<int>("PytanieId")
                        .HasColumnType("int");

                    b.Property<string>("TrescOdpowiedzi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PytanieId");

                    b.ToTable("Odpowiedzi");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.PrzypisanyTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDostepnosci")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrzypisania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWygasniecia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NauczycielId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("UczenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NauczycielId");

                    b.HasIndex("TestId");

                    b.HasIndex("UczenId");

                    b.ToTable("PrzypisaneTesty");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Pytanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAutora")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaPunktow")
                        .HasColumnType("int");

                    b.Property<string>("TrescPytania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypPytania")
                        .HasColumnType("int");

                    b.Property<int?>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAutora");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Pytania");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Rola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Nauczyciel"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Uczen"
                        });
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("CzasTrwaniaMinuty")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAutora")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgZdania")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Testy");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.TestPytanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumerKolejnosci")
                        .HasColumnType("int");

                    b.Property<int>("PytanieId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PytanieId");

                    b.HasIndex("TestId");

                    b.ToTable("TestPytania");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolaId");

                    b.ToTable("Uzytkownicy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Haslo = "admin123",
                            Imie = "Admin",
                            Login = "admin",
                            Nazwisko = "Systemowy",
                            RolaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Haslo = "123",
                            Imie = "Jan",
                            Login = "nauczyciel",
                            Nazwisko = "Kowalski",
                            RolaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Haslo = "123",
                            Imie = "Adam",
                            Login = "uczen",
                            Nazwisko = "Nowak",
                            RolaId = 3
                        });
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.WynikTestu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CzasRozwiazywaniaMinuty")
                        .HasColumnType("int");

                    b.Property<bool?>("CzyProbny")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyZdane")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataRozpoczecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("LiczbaPunktow")
                        .HasColumnType("int");

                    b.Property<decimal>("Ocena")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("Procent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("WynikiTestow");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.LogLogowania", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("LogiLogowan")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.LogRozwiazywaniaTestu", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.PrzypisanyTest", "PrzypisanyTest")
                        .WithMany("LogiRozwiazywaniaTestow")
                        .HasForeignKey("PrzypisanyTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("LogiRozwiazywaniaTestow")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrzypisanyTest");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Odpowiedz", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Pytanie", "Pytanie")
                        .WithMany("Odpowiedzi")
                        .HasForeignKey("PytanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pytanie");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.PrzypisanyTest", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Nauczyciel")
                        .WithMany("PrzypisaneTestyNauczyciela")
                        .HasForeignKey("NauczycielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Test", "Test")
                        .WithMany("PrzypisaneTesty")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Uczen")
                        .WithMany("PrzypisaneTestyUcznia")
                        .HasForeignKey("UczenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nauczyciel");

                    b.Navigation("Test");

                    b.Navigation("Uczen");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Pytanie", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Autor")
                        .WithMany()
                        .HasForeignKey("IdAutora")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", null)
                        .WithMany("Pytania")
                        .HasForeignKey("UzytkownikId");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Test", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Autor")
                        .WithMany("Testy")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.TestPytanie", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Pytanie", "Pytanie")
                        .WithMany("TestPytania")
                        .HasForeignKey("PytanieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Test", "Test")
                        .WithMany("TestPytania")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pytanie");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Uzytkownik", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Rola", "Rola")
                        .WithMany("Uzytkownicy")
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.WynikTestu", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Test", "Test")
                        .WithMany("WynikiTestow")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("WynikiTestow")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.PrzypisanyTest", b =>
                {
                    b.Navigation("LogiRozwiazywaniaTestow");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Pytanie", b =>
                {
                    b.Navigation("Odpowiedzi");

                    b.Navigation("TestPytania");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Rola", b =>
                {
                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Test", b =>
                {
                    b.Navigation("PrzypisaneTesty");

                    b.Navigation("TestPytania");

                    b.Navigation("WynikiTestow");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Uzytkownik", b =>
                {
                    b.Navigation("LogiLogowan");

                    b.Navigation("LogiRozwiazywaniaTestow");

                    b.Navigation("PrzypisaneTestyNauczyciela");

                    b.Navigation("PrzypisaneTestyUcznia");

                    b.Navigation("Pytania");

                    b.Navigation("Testy");

                    b.Navigation("WynikiTestow");
                });
#pragma warning restore 612, 618
        }
    }
}
