// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemEgzaminow.Data.Context;

#nullable disable

namespace SystemEgzaminow.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810175448_AddSposobOcenianiaToPrzypisanyTest")]
    partial class AddSposobOcenianiaToPrzypisanyTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Klasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NazwaKlasy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RokSzkolny")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NazwaKlasy", "RokSzkolny")
                        .IsUnique();

                    b.ToTable("Klasy");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.LogLogowania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CzySukces")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataLogowania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataWylogowania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sesja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("LogiLogowan");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.LogRozwiazywaniaTestu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataZdarzenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrzypisanyTestId")
                        .HasColumnType("int");

                    b.Property<string>("TypZdarzenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrzypisanyTestId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("LogiRozwiazywaniaTestu");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Odpowiedz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyPoprawna")
                        .HasColumnType("bit");

                    b.Property<int?>("LiczbaPunktow")
                        .HasColumnType("int");

                    b.Property<int>("PytanieId")
                        .HasColumnType("int");

                    b.Property<string>("TrescOdpowiedzi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PytanieId");

                    b.ToTable("Odpowiedzi");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.PrzypisanyTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyPokazacWynikPoZakonczeniu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataDostepnosci")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrzypisania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataWygasniecia")
                        .HasColumnType("datetime2");

                    b.Property<string>("InformacjaKoncowa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InformacjaStartowa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LiczbaProb")
                        .HasColumnType("int");

                    b.Property<int>("NauczycielId")
                        .HasColumnType("int");

                    b.Property<int>("SposobOceniania")
                        .HasColumnType("int");

                    b.Property<int>("SposobWyswietlaniaWyniku")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("UczenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NauczycielId");

                    b.HasIndex("TestId");

                    b.HasIndex("UczenId");

                    b.ToTable("PrzypisaneTesty");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Pytanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyZarchiwizowane")
                        .HasColumnType("bit");

                    b.Property<int>("IdAutora")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaPunktow")
                        .HasColumnType("int");

                    b.Property<string>("SciezkaZdjecia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrescPytania")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypPytania")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAutora");

                    b.ToTable("Pytania");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Rola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Nauczyciel"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Uczen"
                        });
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.RozwiazanaOdpowiedz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyPoprawna")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyWybranaPrzezUcznia")
                        .HasColumnType("bit");

                    b.Property<int?>("IdOdpowiedziZrodlowej")
                        .HasColumnType("int");

                    b.Property<int>("IdRozwiazanegoPytania")
                        .HasColumnType("int");

                    b.Property<int>("Kolejnosc")
                        .HasColumnType("int");

                    b.Property<string>("KomentarzNauczyciela")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LiczbaPunktow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrescOdpowiedzi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TrescOdpowiedziUcznia")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("IdRozwiazanegoPytania");

                    b.ToTable("RozwiazaneOdpowiedzi");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.RozwiazanePytanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAutoraPytania")
                        .HasColumnType("int");

                    b.Property<int?>("IdPytaniaZrodlowego")
                        .HasColumnType("int");

                    b.Property<int>("IdWynikuTestu")
                        .HasColumnType("int");

                    b.Property<int>("Kolejnosc")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaPunktowMax")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaPunktowZdobytych")
                        .HasColumnType("int");

                    b.Property<string>("TrescPytania")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("TypPytania")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdWynikuTestu", "Kolejnosc")
                        .IsUnique();

                    b.ToTable("RozwiazanePytania");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CzasTrwaniaMinuty")
                        .HasColumnType("int");

                    b.Property<bool>("CzyZarchiwizowany")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAutora")
                        .HasColumnType("int");

                    b.Property<int>("IdTypuTestu")
                        .HasColumnType("int");

                    b.Property<bool>("LosujKolejnoscOdpowiedzi")
                        .HasColumnType("bit");

                    b.Property<bool>("LosujKolejnoscPytan")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgZdania")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAutora");

                    b.HasIndex("IdTypuTestu");

                    b.ToTable("Testy");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.TestPytanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumerKolejnosci")
                        .HasColumnType("int");

                    b.Property<int>("PytanieId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PytanieId");

                    b.HasIndex("TestId", "PytanieId")
                        .IsUnique();

                    b.ToTable("TestPytania");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.TypTestu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NazwaTypu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NazwaTypu")
                        .IsUnique();

                    b.ToTable("TypyTestow");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NazwaTypu = "Kartkówka"
                        },
                        new
                        {
                            Id = 2,
                            NazwaTypu = "Sprawdzian"
                        },
                        new
                        {
                            Id = 3,
                            NazwaTypu = "Test ćwiczeniowy"
                        },
                        new
                        {
                            Id = 4,
                            NazwaTypu = "Olimpiada"
                        },
                        new
                        {
                            Id = 5,
                            NazwaTypu = "Wejściówka"
                        },
                        new
                        {
                            Id = 6,
                            NazwaTypu = "Kolokwium"
                        },
                        new
                        {
                            Id = 7,
                            NazwaTypu = "Egzamin"
                        },
                        new
                        {
                            Id = 8,
                            NazwaTypu = "Test certyfikacyjny"
                        },
                        new
                        {
                            Id = 9,
                            NazwaTypu = "Egzamin certyfikacyjny"
                        },
                        new
                        {
                            Id = 10,
                            NazwaTypu = "Inny"
                        });
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlasaId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlasaId");

                    b.HasIndex("RolaId");

                    b.ToTable("Uzytkownicy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Haslo = "admin123",
                            Imie = "Admin",
                            Login = "admin",
                            Nazwisko = "Systemowy",
                            RolaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Haslo = "123",
                            Imie = "Jan",
                            Login = "nauczyciel",
                            Nazwisko = "Kowalski",
                            RolaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Haslo = "123",
                            Imie = "Adam",
                            Login = "uczen",
                            Nazwisko = "Nowak",
                            RolaId = 3
                        });
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.WynikTestu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CzasRozwiazywaniaMinuty")
                        .HasColumnType("int");

                    b.Property<bool?>("CzyProbny")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyZdane")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataRozpoczecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("LiczbaPunktow")
                        .HasColumnType("int");

                    b.Property<int>("MaksymalnaLiczbaPunktow")
                        .HasColumnType("int");

                    b.Property<decimal>("Ocena")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("Procent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("PrzypisanyTestId")
                        .HasColumnType("int");

                    b.Property<int?>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrzypisanyTestId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("WynikiTestow");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.LogLogowania", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("LogiLogowan")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.LogRozwiazywaniaTestu", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.PrzypisanyTest", "PrzypisanyTest")
                        .WithMany("LogiRozwiazywaniaTestow")
                        .HasForeignKey("PrzypisanyTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("LogiRozwiazywaniaTestow")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrzypisanyTest");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Odpowiedz", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Pytanie", "Pytanie")
                        .WithMany("Odpowiedzi")
                        .HasForeignKey("PytanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pytanie");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.PrzypisanyTest", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Nauczyciel")
                        .WithMany("PrzypisaneTestyNauczyciela")
                        .HasForeignKey("NauczycielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Test", "Test")
                        .WithMany("PrzypisaneTesty")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Uczen")
                        .WithMany("PrzypisaneTestyUcznia")
                        .HasForeignKey("UczenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nauczyciel");

                    b.Navigation("Test");

                    b.Navigation("Uczen");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Pytanie", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Autor")
                        .WithMany("Pytania")
                        .HasForeignKey("IdAutora")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.RozwiazanaOdpowiedz", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.RozwiazanePytanie", "RozwiazanePytanie")
                        .WithMany("RozwiazaneOdpowiedzi")
                        .HasForeignKey("IdRozwiazanegoPytania")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RozwiazanePytanie");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.RozwiazanePytanie", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.WynikTestu", "WynikTestu")
                        .WithMany("RozwiazanePytania")
                        .HasForeignKey("IdWynikuTestu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WynikTestu");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Test", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Autor")
                        .WithMany("Testy")
                        .HasForeignKey("IdAutora")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.TypTestu", "TypTestu")
                        .WithMany("Testy")
                        .HasForeignKey("IdTypuTestu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("TypTestu");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.TestPytanie", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Pytanie", "Pytanie")
                        .WithMany("TestPytania")
                        .HasForeignKey("PytanieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemEgzaminow.Core.Models.Test", "Test")
                        .WithMany("TestPytania")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pytanie");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Uzytkownik", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.Klasa", "Klasa")
                        .WithMany("Uczniowie")
                        .HasForeignKey("KlasaId");

                    b.HasOne("SystemEgzaminow.Core.Models.Rola", "Rola")
                        .WithMany("Uzytkownicy")
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klasa");

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.WynikTestu", b =>
                {
                    b.HasOne("SystemEgzaminow.Core.Models.PrzypisanyTest", "PrzypisanyTest")
                        .WithMany("WynikiTestow")
                        .HasForeignKey("PrzypisanyTestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SystemEgzaminow.Core.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("WynikiTestow")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrzypisanyTest");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Klasa", b =>
                {
                    b.Navigation("Uczniowie");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.PrzypisanyTest", b =>
                {
                    b.Navigation("LogiRozwiazywaniaTestow");

                    b.Navigation("WynikiTestow");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Pytanie", b =>
                {
                    b.Navigation("Odpowiedzi");

                    b.Navigation("TestPytania");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Rola", b =>
                {
                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.RozwiazanePytanie", b =>
                {
                    b.Navigation("RozwiazaneOdpowiedzi");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Test", b =>
                {
                    b.Navigation("PrzypisaneTesty");

                    b.Navigation("TestPytania");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.TypTestu", b =>
                {
                    b.Navigation("Testy");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.Uzytkownik", b =>
                {
                    b.Navigation("LogiLogowan");

                    b.Navigation("LogiRozwiazywaniaTestow");

                    b.Navigation("PrzypisaneTestyNauczyciela");

                    b.Navigation("PrzypisaneTestyUcznia");

                    b.Navigation("Pytania");

                    b.Navigation("Testy");

                    b.Navigation("WynikiTestow");
                });

            modelBuilder.Entity("SystemEgzaminow.Core.Models.WynikTestu", b =>
                {
                    b.Navigation("RozwiazanePytania");
                });
#pragma warning restore 612, 618
        }
    }
}
